version: '3.8'

services:
  iss-tracker-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=midterm_332.py
    command: flask run --host=0.0.0.0
